SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEEED = 300  # degrees per second
PLAYER_THRUST = 200  # pixels per second squared

SHOT_RADIUS = 5
SHOT_SPEED = 500  # pixels per second
SHOOT_COOLDOWN = 0.3  # seconds between shots

ASTEROID_SPLIT_COUNT = 2
ASTEROID_SPLIT_ANGLE_MIN = 20
ASTEROID_SPLIT_ANGLE_MAX = 50
ASTEROID_MIN_RADIUS = 15
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.5


